### ISSUE TITLE
Can not login with identi.ca account! Socket Hang Up!

### ISSUE THREAD

**Issue by Bersam** [e14n/openfarmgame#57]
it get error on openfarmgame.com/login so i thought it might be with openfarmgame platfrom error! come on! my potatos need water :D

Express
500 Error: socket hang up

```
at SecurePair.error (tls.js:966:15)
at EncryptedStream.CryptoStream._done (tls.js:450:17)
at EncryptedStream.CryptoStream._pull (tls.js:595:12)
at SecurePair.cycle (tls.js:884:20)
at EncryptedStream.CryptoStream.end (tls.js:423:13)
at Socket.onend (stream.js:66:10)
at Socket.EventEmitter.emit (events.js:126:20)
at TCP.onread (net.js:418:51)
```

**Comment by Bersam** [comment]
Oh, i think that because identi.ca is down now, come on we need better error for such things :)
