### ISSUE TITLE
500 Error: Not enough coins to water something.

### ISSUE THREAD

**Issue by johand** [e14n/openfarmgame#60]
```
Express
500 Error: Not enough coins to water something.
at exports.handleWater (/home/ubuntu/openfarmgame/routes/index.js:302:14)
at callbacks (/home/ubuntu/openfarmgame/node_modules/express/lib/router/index.js:272:11)
at async.waterfall.userIsOwner (/home/ubuntu/openfarmgame/app.js:272:17)
at callbacks (/home/ubuntu/openfarmgame/node_modules/express/lib/router/index.js:272:11)
at async.waterfall.reqPlot (/home/ubuntu/openfarmgame/app.js:251:21)
at DatabankObject.subClass.Cls.get (/home/ubuntu/openfarmgame/node_modules/databank/lib/databankobject.js:110:33)
at passThru0 (/home/ubuntu/openfarmgame/node_modules/databank/lib/databankobject.js:44:5)
at DatabankObject.subClass.Cls.get (/home/ubuntu/openfarmgame/node_modules/databank/lib/databankobject.js:106:27)
at bank.read (/home/ubuntu/openfarmgame/node_modules/databank/node_modules/databank-mongodb/lib/mongodb.js:363:21)
at Collection.findOne (/home/ubuntu/openfarmgame/node_modules/databank/node_modules/databank-mongodb/node_modules/mongodb/lib/mongodb/collection.js:1010:5)
```

that happens when i try to watering the harvest with no money

**Comment by ghost** [comment]
![1](https://cloud.githubusercontent.com/assets/2771136/3399178/5a9dfe7e-fd39-11e3-8915-547b3984209e.png)
